# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# SERVER
# ===============================
server.servlet.context-path=/api/v1.0
server.port=${PORT:8080}

# ===============================
# AWS S3
# ===============================
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.bucket.name=${AWS_BUCKET_NAME}

# ===============================
# JWT
# ===============================
jwt.secret.key=${JWT_SECRET_KEY}

# ===============================
# RAZORPAY
# ===============================
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}