 spring.datasource.url=jdbc:mysql://localhost:3306/billing_app
 spring.datasource.username=root
 spring.datasource.password=shreeshail_miragi18



 spring.jpa.hibernate.ddl-auto=update
 server.servlet.context-path=/api/v1.0



 aws.access.key=rzp_test_T3DpkYtgHAORpv
 aws.secret.key=xR4w81iW7kJB16MxEUfSLHCd
 aws.region=india
 aws.bucket.name=dfvd


jwt.secret.key=thsiismysptrinqeh5sdfvbnuytree345678ikjhcds3456t7u8iowfmnehvwecd6g

razorpay.key.id = rzp_test_SYezEEO1NX7LBF
razorpay.key.secret = PTZJTdtBgMaHqo46kCgnF9RA

